[package]
name = "omgbot"
version = "0.1.0"
authors = ["Andy Kurnia"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#board = { path = "../board" }
board = { git = "git://github.com/andy-k/board", branch = "bot/0.1" }
nats = "0.8.6"
prost = "0.7.0"

[build-dependencies]
prost-build = "0.7.0"
