[package]
name = "omgbot"
version = "0.1.0"
authors = ["Andy Kurnia"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 3

[dependencies]
async-nats = "0.9.8"
prost = "0.7.0"
rand = "0.8.3"
rand_chacha = "0.3.0"
tokio = { version = "1.4.0", features = ["full"] }
wolges = { path = "wolges" }

[build-dependencies]
prost-build = "0.7.0"
