[package]
name = "omgbot"
version = "0.1.0"
authors = ["Andy Kurnia"]
edition = "2021"
license = "MIT"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 3

[dependencies]
async-nats = "0.10.1"
prost = "0.8.0"
rand = "0.8.4"
rand_chacha = "0.3.1"
tokio = { version = "1.12.0", features = ["full"] }
wolges = { path = "wolges" }

[build-dependencies]
prost-build = "0.8.0"
