[package]
name = "omgbot"
version = "0.1.0"
authors = ["Andy Kurnia"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 3

[dependencies]
async-nats = "0.9.2"
prost = "0.7.0"
rand = "0.8.3"
rand_chacha = "0.3.0"
tokio = { version = "1.1.1", features = ["full"] }
#wolges = { path = "../wolges" }
wolges = { git = "git://github.com/andy-k/wolges", branch = "bot/0.4" }

[build-dependencies]
prost-build = "0.7.0"
