[package]
name = "omgbot"
version = "0.1.0"
authors = ["Andy Kurnia"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 3

[dependencies]
async-nats = "0.9.1"
#board = { path = "../board" }
board = { git = "git://github.com/andy-k/board", branch = "bot/0.2" }
prost = "0.7.0"
rand = "0.8.2"
rand_chacha = "0.3.0"
tokio = { version = "1.0.2", features = ["full"] }

[build-dependencies]
prost-build = "0.7.0"
