[package]
name = "omgbot"
version = "0.1.0"
authors = ["Andy Kurnia"]
edition = "2021"
default-run = "omgbot"
license = "MIT"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 3

[dependencies]
async-nats = "0.22.1"
env_logger = "0.9.3"
futures-util = "0.3.25"
log = "0.4.17"
prost = "0.11.2"
rand = "0.8.5"
rand_chacha = "0.3.1"
reqwest = { version = "0.11.12", features = ["blocking"] }
tokio = { version = "1.21.2", features = ["full"] }
wolges = { path = "wolges" }

[build-dependencies]
prost-build = "0.11.2"

[[bin]]
name = "omgbot"
path = "src/main.rs"

[[bin]]
name = "bvb"
path = "src/bvb.rs"
