name: Rust
'on':
  push:
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
    runs-on: "${{ matrix.os }}"
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/checkout@v3
      with:
        repository: domino14/macondo
        path: macondo
    - name: Link proto
      run: ln -s ../macondo/api/proto/macondo/macondo.proto src
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Version
      run: cargo version
    - name: Clippy
      run: cargo clippy --release --verbose
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose
